import { getTodos } from '@/api/getTodos';
import AuthGuard from '@/components/AuthGuard';
import { Button } from '@/components/ui';
import { useAuth } from '@/hooks';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
  const { logIn, logOut, user } = useAuth();

  useEffect(() => {
    if (user) {
      getTodos().then((data) => {
        console.log(data);
      });
    }
  }, [user]);

  useEffect(() => {
    // fetch('/api/socket').finally(() => {
    //   const socket = io();
    //   debugger;
    //   socket.on('a user connected', () => {
    //     console.log('a user connected');
    //   });
    // });
  }, []);

  // const handleLogin = async () => {
  //   const { data, error } = await signInWithGoogle();
  //   console.log(data);
  // };
  // const handleLogout = async () => {
  //   signout();
  //   // await supabaseClient.auth.signOut();
  // };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-screen h-screen flex justify-center items-center">
          <Button onClick={() => logIn()}>Login</Button>
          <Button onClick={() => logOut()}>Logout</Button>
        </div>
        <AuthGuard>Logged In</AuthGuard>
      </main>
    </>
  );
}
